#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && (flake8 --format=html --htmldir=flake-report --exclude 'system_test,src/antlr/Comp0010ShellParser.py,src/antlr/Comp0010ShellVisitor.py,src/antlr/Comp0010ShellLexer.py' || true) && cd flake-report/ && python3 -m http.server
